stages:
  - analyse
  - build

include:
  - project: rutoken/dev/devops/checker/code-quality
    ref: latest
    file: /code-quality.yaml

variables:
  VAULT_ADDR: "https://vault.aktivco.ru"


.vault_provision_secrets: &vault_secrets
  - PROJECT_ROLE="ci-swift-package"
  - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${PROJECT_ROLE} jwt=${CI_JOB_JWT})"

  - SSH_PRIVATE_KEY="${HOME}/.ssh/id_rsa"

  - vault kv get -field=private ci/apple/identity/ssh-key > ${SSH_PRIVATE_KEY}
  - chmod 0600 ${SSH_PRIVATE_KEY}

  - vault token revoke -self

code_quality:
  stage: analyse
  extends: .code-quality

build:
  stage: build
  tags: [vagrant-darwin]
  variables:
    RT_CI_VAGRANT_BOX_NAME: rutoken/macos
    RT_CI_VAGRANT_BOX_VERSION: 1.6.3
    RT_CI_VAGRANT_BOX_CPUS: 2
    RT_CI_VAGRANT_BOX_MEMORY: 4096
  before_script:
    - *vault_secrets

    - ip=$(dig scm.aktivco.ru +short)
    - ssh-keyscan scm.aktivco.ru,$ip >> ~/.ssh/known_hosts
  script:
    - |
      xcodebuild clean build  -scheme rt-pcsc-wrapper \
                              -destination generic/platform=iOS \
                              -scmProvider system
